version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: websocket_app
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/websocketApp

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
